// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDihBStjp_-QVDDO3nCLqwAVbffwwXTQ4M',
    appId: '1:152899558951:web:5f3183ff8ee9acb2f7f802',
    messagingSenderId: '152899558951',
    projectId: 'skolyozapp',
    authDomain: 'skolyozapp.firebaseapp.com',
    storageBucket: 'skolyozapp.appspot.com',
    measurementId: 'G-YYZVNWJ3DR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8TBwIc2y3xvUYHqfeDkgYiAmcfKqaGV0',
    appId: '1:152899558951:android:d375240a67f4c2e9f7f802',
    messagingSenderId: '152899558951',
    projectId: 'skolyozapp',
    storageBucket: 'skolyozapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEXnrB7JWYjeUk7S2dBJOrcu0EuqAA_Hc',
    appId: '1:152899558951:ios:fdba02d5392ea4f3f7f802',
    messagingSenderId: '152899558951',
    projectId: 'skolyozapp',
    storageBucket: 'skolyozapp.appspot.com',
    iosBundleId: 'com.example.skolyozapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEXnrB7JWYjeUk7S2dBJOrcu0EuqAA_Hc',
    appId: '1:152899558951:ios:fdba02d5392ea4f3f7f802',
    messagingSenderId: '152899558951',
    projectId: 'skolyozapp',
    storageBucket: 'skolyozapp.appspot.com',
    iosBundleId: 'com.example.skolyozapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDihBStjp_-QVDDO3nCLqwAVbffwwXTQ4M',
    appId: '1:152899558951:web:ee3a29b144fe5b00f7f802',
    messagingSenderId: '152899558951',
    projectId: 'skolyozapp',
    authDomain: 'skolyozapp.firebaseapp.com',
    storageBucket: 'skolyozapp.appspot.com',
    measurementId: 'G-VED67JEQJV',
  );

}